# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build docker container
      - name: Build docker image
        run: docker build . -t pgmodeler

      # Run docker container
      - name: Run docker image
        run: docker run pgmodeler -v ${{ github.workspace }}/pgmodeler:/opt/pgmodeler

      # prepare artifact
      - name: Prepare artifact
        run: tar -cvzf ${{ github.workspace }}/pgmodeler-dist.tar.gz ${{ github.workspace }}/pgmodeler/

      # upload artifact
      - uses: actions/upload-artifact@v2-preview
        with:
          name: pgmodeler
          path: ${{ github.workspace }}/pgmodeler-dist.tar.gz
